version: '3'
services:
  server:
    # will build ./docker/server/Dockerfile
    build: ./docker/server
    ports:
      - "5000:5000"
  
  client:
    # will build ./docker/client/Dockerfile
    build: ./docker/client
    ports:
      - "3306:3306"